// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpopoqnxydaigaxecuzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wb3BvcW54eWRhaWdheGVjdXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTkwMjcsImV4cCI6MjA2MDU3NTAyN30.7HnfN5uMU7TKC9uqvrWMoJnlBkvUoYxG-z6pNyGzV_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);